image: node:8

before_script:
- npm install

#cache:
#    paths:
#    - node_modules/

test:
    stage: test
    script:
    - npm run test

staging:
    stage: deploy
    script:
    - npm version from-git
    - npm run build
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm publish --tag beta
    only:
    - tags
    - triggers
    - develop@HeavyLightStudios/HLSWebComponents/Heavy-Navbar

production:
    stage: deploy
    script:
    - npm version from-git
    - npm run build
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm publish
    only:
    - tags
    - triggers
    - master@HeavyLightStudios/HLSWebComponents/Heavy-Navbar
