image: node:latest

cache:
    paths:
    - node_modules/

build:
    stage: build
    script:
      - npm install

setNextRelease:
    stage: build
    script:
    - $NPM_TAG = "next"
    only:
    - develop

setLatestRelease:
    stage: build
    script:
    - $NPM_TAG = "latest"
    only:
    - master


test:
    stage: test
    script:
    - npm run test

release:
    stage: deploy
    only:
        - tags
    script:
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm publish --tag $NPM_TAG

