image: node:8

before_script:
- npm install

cache:
    paths:
    - node_modules/

test:
    stage: test
    script:
    - npm run test

production:
    stage: deploy
    script:
    - npm version from-git
    - npm run build
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm publish
    only:
    - tags
    - triggers
