image: node:latest

cache:
    paths:
    - node_modules/

build:
    stage: build
    script:
      - npm install

test:
    stage: test
    script:
    - npm run test

staging:
    stage: deploy
    script:
    - npm version from-git --force
    - npm run build
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm publish --tag beta
    only:
    - tags
    except:
    - ^(?!.*\bmaster\b).*$


production:
    stage: deploy
    script:
    - npm version from-git --force
    - npm run build
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm publish
    only:
    - tags
    except:
    - ^(?!.*\bdevelop\b).*$


