/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface HeavyNavbar {
        "itemCount": number;
        "logo": string;
        "menuItems": string;
        "position": string;
    }
}
declare global {
    interface HTMLHeavyNavbarElement extends Components.HeavyNavbar, HTMLStencilElement {
    }
    var HTMLHeavyNavbarElement: {
        prototype: HTMLHeavyNavbarElement;
        new (): HTMLHeavyNavbarElement;
    };
    interface HTMLElementTagNameMap {
        "heavy-navbar": HTMLHeavyNavbarElement;
    }
}
declare namespace LocalJSX {
    interface HeavyNavbar {
        "itemCount"?: number;
        "logo"?: string;
        "menuItems"?: string;
        "position"?: string;
    }
    interface IntrinsicElements {
        "heavy-navbar": HeavyNavbar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "heavy-navbar": LocalJSX.HeavyNavbar & JSXBase.HTMLAttributes<HTMLHeavyNavbarElement>;
        }
    }
}
