/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface HeavyNavbar {
    'itemCount': number;
    'logo': string;
    'menuItems': string;
    'position': string;
  }
  interface HeavyNavbarAttributes extends StencilHTMLAttributes {
    'itemCount'?: number;
    'logo'?: string;
    'menuItems'?: string;
    'position'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'HeavyNavbar': Components.HeavyNavbar;
  }

  interface StencilIntrinsicElements {
    'heavy-navbar': Components.HeavyNavbarAttributes;
  }


  interface HTMLHeavyNavbarElement extends Components.HeavyNavbar, HTMLStencilElement {}
  var HTMLHeavyNavbarElement: {
    prototype: HTMLHeavyNavbarElement;
    new (): HTMLHeavyNavbarElement;
  };

  interface HTMLElementTagNameMap {
    'heavy-navbar': HTMLHeavyNavbarElement
  }

  interface ElementTagNameMap {
    'heavy-navbar': HTMLHeavyNavbarElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
