/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
/* tslint:disable */

import '@stencil/core';




declare global {
  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}

  namespace StencilComponents {

    interface HeavyNavbar {
      'itemCount': number;
      'logo': string;
      'menuItems': string;
      'position': string;
    }
  }


    interface HTMLHeavyNavbarElement extends StencilComponents.HeavyNavbar, HTMLStencilElement {}

    var HTMLHeavyNavbarElement: {
      prototype: HTMLHeavyNavbarElement;
      new (): HTMLHeavyNavbarElement;
    };
    

  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {
    'heavy-navbar': JSXElements.HeavyNavbarAttributes;
    }
  }

  namespace JSXElements {

    export interface HeavyNavbarAttributes extends HTMLAttributes {
      'itemCount'?: number;
      'logo'?: string;
      'menuItems'?: string;
      'position'?: string;
    }
  }

  interface HTMLElementTagNameMap {
    'heavy-navbar': HTMLHeavyNavbarElement
  }

  interface ElementTagNameMap {
    'heavy-navbar': HTMLHeavyNavbarElement;
  }
}
declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;